Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Please, enter your full name");
string last_name = Console.ReadLine();
string first_name = Console.ReadLine();
string middle_name = Console.ReadLine();
Console.BackgroundColor = ConsoleColor.Red;
Console.Write("Hello, ");
Console.Write(last_name + " ");
Console.Write(first_name + " ");
Console.WriteLine(middle_name);
Console.ResetColor();
